---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alehzakharau.
--- DateTime: 3/3/23 11:24 PM
---

local M = {}


local DISPLAY_WIDTH = tonumber(sys.get_config("display.width")) or 960
local DISPLAY_HEIGHT = tonumber(sys.get_config("display.height")) or 640
local UPDATE_FREQUENCY = tonumber(sys.get_config("display.update_frequency") or sys.get_config("display.frame_cap"))

function M.get_display_size()
    return DISPLAY_WIDTH, DISPLAY_HEIGHT
end

return M